name: Deploy SelfStudyReport

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploying SelfStudyReport to  Production
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1  # Updated version
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          protocol: ftps  # Enable FTPS (explicit TLS)
          # port: 21      # Uncomment if your server uses a non-standard port
          # passive: true # Enable if behind a firewall
